spring:
  datasource:
    url: jdbc:mysql://localhost:3306/buysell
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  freemarker:
    expose-request-attributes: true
