<!DOCTYPE html>
<html>
<head>
    <title>BUYSELL</title>
</head>
<body>
<h1>BUYSELL</h1>
<hr>
<h2>AUTHORIZING</h2>
<hr>
<form action="/login" method="post">
    Email: <input type="email" name="username"><br><br>
    Password: <input type="password" name="password"><br><br>
    <input type="hidden" name="_csrf" value="${_csrf.token}">
    <input type="submit" value="Let's go!">
</form><br>
<a href="/">HOME PAGE</a> | <a href="/registration">REGISTRATION</a>
</body>
</html>